### ISSUE TITLE
General Report Debugging

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#122]
Applied to All Reports:

**Header**
- Please include the MOH Logo in the top banner (to the left of Jordan)

**Boxes**
- Please rename any label of "Demographics" box title to Age Group for the age group boxes
- Please include y-axis label of _No of cases_ and x-axis label of _Age Group_ in the Age Group box
- Please include a data table below the chart in the Age Group box
- Please include a data table below the chart in the Gender box

**More Information**
- Please remove the two “ands” in the second para of the More Information box so it reads _“best practice prescribing and real-time reporting of information”_

**Footer**
- Please ensure the time and date are included in the footer, **and it is stated as UTC**
- Please include MOH email address (iers@moh.gov.jo) in the _“For more information, please email: iers@moh.gov.jo”_

**Comment by mrjb** [comment]
@johnhaskew This all seems to make sense. Just one clarification...
 "please ensure time and date are included in the footer" this should already be happening since I made the change to include the "up to date as of" message... and it should be UTC. However, perhaps this wasn't deployed when you were looking at it?

**Comment by johnhaskew** [comment]
So yes thank you - it is included but doesn't specify UTC. If we could please just include this also.

**Comment by mrjb** [comment]
This is deployed.
