### ISSUE TITLE
NCD Report changes

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#124]
**NCD Profile**

- Please ensure the date range fits on one line (either next to the title or below)
- Please remove % five years of age in the Key Findings, so the second bullet reads:
_X% female and X% male_ 

**NCD Report**

The title is spelt incorrectly - Non Communciable Diseases Report
If we can please update to -  **Non Communicable Diseases Report**

Table 1. (for Hypertension and Diabetes)
- Total column to be moved from the last to be the first column in the table
- Spacing of the rows to be increased so the table fills the page
- Font size of last row to be increased
- Light line to be included to demarcate columns (as is done for rows)

Table 2. (for Hypertension and Diabetes)
- Spacing of the rows to be increased so the table fills the page
- Font size of last row to be increased
- Light line to be included to demarcate columns (as is done for rows)
- Labelling of overweight column to be _overweight (BMI = 25 - 29.9) (%)_
- Labelling of obese column to be _obese (BMI = 30 or more) (%)_

**Comment by johnhaskew** [comment]
Hi Jyri - thanks so much for helping update the NCD report. Please note it is the Total Column that needs to move to the front, not the Row. 

I think we have moved the Total Row to the top of the table currently, but it should remain at the bottom.

It is the Total column that should move from the right side of the table to the left (as we do already in Table 2).

Many thanks.

**Comment by jsoppela** [comment]
Hi John - Which branch are you looking at? I am working with branch issue124 and have not touched the order of columns yet. This is because the order of columns is currently dictated by the data structure returned by the API instead of the html template in this repository. We'll figure out tomorrow how to reorder them with @mrjb without building another redundant logic layer in the table.

Instead of changing fonts, I've bolded the total numbers and will change their background colour to match Table 2: Distribution of diabetes patients. Let's see how that looks like and change it if necessary. My guess is that different fonts in same table would look quite confusing.

**Comment by mrjb** [comment]
I was thinking about this after john spoke to me... It's because I made the change you requested to the api data? That has been deployed now, and changed the order of things in the deployment.

**Comment by jsoppela** [comment]
I've made a new branch issue124 for api and reordered the columns. Let's have a look tomorrow whether it looks right. The percentages in Table 2 are divided into two rows, I think this needs to be addressed.

**Comment by jsoppela** [comment]
Changes have now been made to branch issue124. Will finish testing and merge the branch.
