### ISSUE TITLE
CD Report changes

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#125]
The x-axis for each epi curve needs to show the whole year (up to week 52) please

**Comment by mrjb** [comment]
Have I understood you correctly? You want to include weeks from now until the end of the current year in every graph in the report? 

...It just it seems very strange to take up a huge amount of report area/paper with empty chart space visualising uncollected/non-existant data.  This will remove visualisation fidelity, distract and appear incredibly messy I think. Perhaps I've not understood what your saying or more likely there are reasons that I am unaware of?

If this is what you want, can I clarify that we want the chart space to be empty for those weeks i.e. no line/data at all,  rather than data with a 0 value, which would presumably be considered misleading and wrong?

**Comment by johnhaskew** [comment]
I agree with you. This is a request specifically from MOH. If you also don't think it will look good, let me go back and tell them. Let's leave it for now and hopefully they will agree with us.

**Comment by mrjb** [comment]
I just think this would be very bad data visualisation, making it harder to comprehend what the data is saying. Not so fussed about what they think "looks good".  If they want it, I can just do it. But it seems very odd and going against everything I've been taught.
