### ISSUE TITLE
SMS alerts need two messages

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#126]
Each alert seems to use two SMS messages, so would be great to truncate so it fits into one text.
We can remove the patient ID and truncate the first line as follows:

**Public Health Surveillance Alert:
Alert:
Date: 
Clinic:
Region:
Gender:
Age:
Alert ID:**

Would that fit into one message?

**Comment by mrjb** [comment]
We have 160 characters to work with in a single text. The above has 86 characters, leaving 74 characters to fit all the other information into. Taking a recent alert from Jordan at random (ce795f), I make the above structure 156 characters. So my guess is that whilst this would help, we will still have some alerts taking up two text messages depending on the length of the region and clinic name and the length of the alert reason. I will have a think about whether we can compress even more, but will otherwise implement this new structure once the other more pressing issues are finished.

**Comment by johnhaskew** [comment]
Great - thanks Jonathan

**Comment by mrjb** [comment]
I have changed the text to the above format and deployed.  I have kept the country in the first line though, because it would make things very confusing for the folk signed up to multiple countries otherwise. Let me know if that is a problem. This format will still help increase the number of alert notifications that only require one sms. 

Further ideas for compression could be picked from the following format:
```
<country> Public Health Surveillance Alert:
<date> | <reason>
Clinic:<clinic> - <region>
Patient: <gender> <age> yrs
Alert ID: <alert-ID>
```
E.g.
```
Madagascar Public Health Surveillance Alert:
Measles | 02 Aug 16
Clinic: Anjara - Aljoun
Patient: male 5 yrs
Alert ID: gsd132
```
In total this structure takes up just 57 characters leaving 103 characters for the actual information - significantly more space.   We can implement none, part or all of this depending on what you like.
