### ISSUE TITLE
Frontend for Timeliness Tab

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#146]
To include Timeliness Tab (same format and UI as completeness).

Data will be acquired by making an api call very similar to the completness tab, except a different aggregation code will be used in the url.

It should look almost exactly like the completeness tab.

**Comment by jonathansberry** [comment]
The backend should be done, see issue #149 for details.

**Comment by mixmixmix** [comment]
I've created branch `timeliness` on frontened and mad. I basically cloned completeness and changed the aggregation function. I cannot see how it works on Madagascar at the moment due to my technical struggle, but @jonathansberry you should be able to see.
How should we call "Reporting sites never reported" table?

**Comment by jonathansberry** [comment]
This has been merged into master.  I will close the issue whilst we focus on the rest of the milestone.

**Comment by mixmixmix** [comment]
Remove "clinics not reporting tab".

**Comment by mixmixmix** [comment]
It's ready now: https://github.com/meerkat-code/meerkat_frontend/pull/169
