### ISSUE TITLE
Completeness doesn't work in Week 1

### ISSUE THREAD

**Issue by mixmixmix** [meerkat-code/meerkat_frontend#195]
API call `http://localhost/api/completeness/reg_1/1/4/3/None/5,6` returns `{}`. I suggest that we address it in the back end. Thoughts @Gulfa, @jonathansberry?

**Comment by Gulfa** [comment]
Hi, this might be due some issues with madagascar data. It has not really been updated over christmas. You get the same problem in Demo?

**Comment by johnhaskew** [comment]
We get the same problem with Jordan too, showing all zeros in the reports and website.

**Comment by Gulfa** [comment]
So there are some data issues which I think should have been sorted out now. There is also a bug in the completeness calculation. Since we show completeness for the week before we are now trying to show completeness for week 0. I.e the code in the api does not support week 1 as you mentioned @mixmixmix. I am flying back to Finland tomorrow, but will see if I have time to take a look at it either tomorrow or on Wednesday.

**Comment by Gulfa** [comment]
@johnhaskew: I have restarted the Jordan server since the API had stopped working. Were the issues for everything? It might be related to some epi-week issues. Since they have wanted epi-weeks to start on Saturdays our program thinks week 1 should start the 7th of January. I know that they want week one to start the 31st of December 2016, so we will need to sort that out.

**Comment by Gulfa** [comment]
So it seems like jordan epi-weeks are currently starting on the 1st of January, the site should sort of be working apart from this.

**Comment by mixmixmix** [comment]
Fixed in https://github.com/meerkat-code/meerkat_api/commit/0c4fee4de16b7a3b6db16897e8c96bd2c953f984
