### ISSUE TITLE
Tablet management service

### ISSUE THREAD

**Issue by jsoppela** [meerkat-code/meerkat_frontend#294]
Since remotely monitoring and managing the tablets is a key requirement for improving the reliability of tablets on the field, we are currently researching options for adopting Google G Suite service for remote tablet management. Google allows discount for nonprofit organizations and verifies the status of nonprofits via an organization called Techsoup. I'm posting updates to this issue as we know about our pricing options.

**Comment by jsoppela** [comment]
The default pricing option for G Suite is $5 per user per month. With our current mobile device fleet this is a major cost and other options need to be researched before committing to the standard rate.

**Comment by Rania80** [comment]
I checked with e-government department chief, he's the one in contact with microsoft and he sent them headlines from me for what we need, they asked for a meeting to talk about their services and they said they might have other options which they'll review with us
I am pushing for a price MOH can annually afford always, not just while project is funded
the main issue is that, we might have focal points in directorates, but their visits to facilities are limited and not always available, and it's not easy for user to deliver devices to directorates, in addition this might waste time not reporting cases
central management and solution seems to fit perfect, but the budget is the issue here

**Comment by jonathansberry** [comment]
All priority issues have been moved to the private meerkat_issues repo.
