### ISSUE TITLE
Jordan emails failed to send on 01/04/2017

### ISSUE THREAD

**Issue by jsoppela** [meerkat-code/meerkat_frontend#301]
https://sentry.io/meerkat-who/meerkat/issues/245301174/

```
Exception: Email request returned not-ok response code: 502
  File "meerkat_abacus/task_queue.py", line 159, in send_report_email
    str(r.status_code)

EMAIL non_communicable_diseases:  Report email request failed.
```

**Comment by jsoppela** [comment]
I checked the online reports and all the NCD reports work fine.

**Comment by jonathansberry** [comment]
The "unique" Hermes ID for the monthly email was being created using a python datetime object and the function strftime('%M') instead of strftime('%m').  The latter correctly yielding the month number, the former actually indicating the "minutes" number instead. The change has been made and committed to development. It should be deployed in Jordan along with other changes today.
